FROM node as npm_install
WORKDIR /app
COPY ./package.json ./
COPY ./package-lock.json ./
COPY ./ .
RUN npm install
RUN npm install -g @angular/cli
ARG ENV=prod
RUN npm run build

FROM nginx:alpine
COPY ./docker/nginx/frontend.site.publico.conf /etc/nginx/conf.d/default.conf
COPY --from=npm_install /app/dist /usr/share/nginx/html
WORKDIR /usr/share/nginx/html
ENTRYPOINT ["nginx", "-g", "daemon off;"]
